### ISSUE TITLE
planetary software badge 

### ISSUE THREAD

**Issue by AndrewAnnex** [planetarysoftware/TSC#11]
As of last meeting we discussed making a "badge" for planetary software TSC affiliated repositories. It is easy to make one using [https://shields.io/](https://shields.io/ ), but we need to decide on a number of options:
1. Label (what appears at left end of shield, could be TSC for instance)
2. Message (affiliate? member? what do we want to say here?)
3. Color (can be any html color or we could just choose blue)
4. Style (default is fine, other options listed on the shields.io page)

see this as an example I quickly made: https://img.shields.io/badge/TSC-affiliate-blue.svg, obviously not final but feel free to iterate here on design!

**Comment by rbeyer** [comment]
Label: So 'TSC' only means something to us, because we know what we are steering, technically.  I think it should be 'planetary software', because that's the org.  I know it makes for a long badge, but that's the right 'brand.'

Message: As far as the message, that's a good question.  'Project' seems to be the language in the TSC organizing docs.  So it would be 'planetary software | project' maybe?  But maybe that's for projects which the TSC directly 'stewards' and projects that we advise are 'affiliates'?  Not sure if the distinction matters for a badge?

**Comment by jessemapel** [comment]
I agree about planetary software and project. I have no real preference on color.

**Comment by AndrewAnnex** [comment]
so how about: 

[![Affiliate](https://img.shields.io/badge/Planetary_Software-Affiliate-blue.svg)](https://img.shields.io/badge/Planetary_Software-Affiliate-blue.svg)  


[![Project](https://img.shields.io/badge/Planetary_Software-Project-blue.svg)](https://img.shields.io/badge/Planetary_Software-Project-blue.svg)

I think it would be neat to use a different color like "ultra violet":

[![Affiliate](https://img.shields.io/badge/Planetary_Software-Affiliate-645394.svg)](https://img.shields.io/badge/Planetary_Software-Affiliate-645394.svg)  

[![Project](https://img.shields.io/badge/Planetary_Software-Project-645394.svg)](https://img.shields.io/badge/Planetary_Software-Project-645394.svg)

**Comment by jessemapel** [comment]
:+1: to "ultra violet"

**Comment by victoronline** [comment]
UV+

**Comment by AndrewAnnex** [comment]
sounds like the uv is liked, @rbeyer we should probably have both "Project" and "Affiliate", maybe different shades of "uv" for one or the other. there is no limit to the number of badges one can make!

**Comment by rbeyer** [comment]
Discussion at the [2019-7-9 meeting](https://github.com/planetarysoftware/TSC/blob/master/meetings/2019-07-09.md) really closed this Issue, and spawned other actions.
