### ISSUE TITLE
PlanetaryPy -> Set up a TC

### ISSUE THREAD

**Issue by jlaura** [planetarysoftware/TSC#21]
- [x] Group needs to form
- [x] People need access (Michael)
- [ ] Conversation has to occur with original owners
- [ ] Someone needs to organize opening a PR on this repo into the Application directory
- [ ] PlanetaryPy needs to determine what they want.

**Comment by rbeyer** [comment]
I'm interested in being a part of a TC here, and would be happy to start the Application PR.  Do we need to wait to do that until the 'conversation' with the original owners happens, or can we move forward?

**Comment by michaelaye** [comment]
so, that's also a question i have, and how exactly we should start the `conversation`.
I have access to planetarypy now and i'm ready to create an email to stake-holders at that domain.
I'm thinking to also include the authors of plio and spiceypy into that conversation, anybody else I forgot? 

Here are some entities that I have in mind maybe as a 2nd step, after having started the conversation? I'm asking for your input if those maybe should be part of it from the beginning:

* [author of pds4-tools](http://sbndev.astro.umd.edu/wiki/Python_PDS4_Tools) ?
* PI of sbpy is already astropy-affiliated so maybe they don't need us 
* PyHAT authors/PIs? Maybe later?

I think the [project lifecycle doc](https://github.com/planetarysoftware/TSC/blob/master/Project-Lifecycle.md) is written pretty well and will help explain what this is about, and together with the fact that our scope clearly describes that the TSC isn't responsibly but only supporting/guiding for TLPs, it should take the edge of for the authors joining a group that they don't really know what it is about, I would make sure to point this out in the initial contact email.

Any other tips for this initial conversation? 
Ross, if you want, we could edit this email together before we send it out, to get the first vibes correctly and not too scary? I'll admit that I tend to jump  ahead with my visions rather too quickly sometimes, which could be off-putting to some people...

**Comment by rbeyer** [comment]
Yeah, I'd start even simpler than that.  I think the first thing is to write an e-mail to the people that you think are the current 'stakeholders' of planetarypy (not any of the future folks that you might want to rope in, just the current cast of players), and state that in order to get planetarypy kickstarted, we (planetarypy) need a governance model, and that we plan to follow the process outlined in planetarysoftware to establish that governance model and apply for incubation status.

After you send that out to the current cast of players, and field questions from them, unless there are any complaints, then I suggest we go ahead and build a 'TSC-like' repo in planetarypy, start populating it, and then make the application to TSC.  Not sure if that is planetarypy/TSC or planetarypy/TC or what, but let's talk at the TSC meeting on Tuesday, and solidify the plan.

**Comment by rbeyer** [comment]
This work has now (appropriately) left the realm of the TSC.  @michaelaye, @AndrewAnnex, and I are working on the first steps to establish a PlanetaryPy TC.  We hope to get a letter out to the current PlanetaryPy org People informing them and inviting them to the TC, getting the TC together, and assembling an application in the next few weeks.

I'm going to close this Issue, since that work should really be on the PlanetaryPy TC, not on the TSC.
